// ─── Models for Source Generator integration tests ──────────────────────────

namespace MapFlow.Tests;

// ─── IMapFrom: class (baseline) ──────────────────────────────────

public class ProductEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public string Sku { get; set; } = string.Empty;
}

public partial class AutoMappedProduct : IMapFrom<ProductEntity>
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public string Sku { get; set; } = string.Empty;
}

public partial class CustomMappedProduct : IMapFrom<ProductEntity>
{
    public int Id { get; set; }
    public string FullName { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public string Sku { get; set; } = string.Empty;

    public void MapFrom(ProductEntity source)
    {
        Id = source.Id;
        FullName = source.Name.ToUpper();
        Price = source.Price;
        Sku = source.Sku;
    }
}

// ─── IMapFrom: record ───────────────────────────────────────────

public record class SourceRecord(int Id, string Name);

public partial record class AutoMappedRecord : IMapFrom<SourceRecord>
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
}

// ─── IMapFrom: struct ───────────────────────────────────────────

public partial struct AutoMappedStruct : IMapFrom<ProductEntity>
{
    public int Id { get; set; }
    public string Name { get; set; }
    public decimal Price { get; set; }
}

// ─── IMapFrom: explicit interface implementation (SG must skip) ─

public partial class ExplicitMappedDto : IMapFrom<ProductEntity>
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;

    void IMapFrom<ProductEntity>.MapFrom(ProductEntity source)
    {
        Id = source.Id;
        Name = source.Name.ToUpper();
    }
}

// ─── IMapTo: auto-generated ─────────────────────────────────────

public class DestDto
{
    public int Id { get; set; }
    public string Value { get; set; } = string.Empty;
}

public partial class AutoMappedSource : IMapTo<DestDto>
{
    public int Id { get; set; }
    public string Value { get; set; } = string.Empty;
    public string Extra { get; set; } = string.Empty; // not mapped (no match)
}

// ─── IMapTo: explicit impl (SG must skip) ───────────────────────

public partial class ExplicitMappedSource : IMapTo<DestDto>
{
    public int Id { get; set; }
    public string Value { get; set; } = string.Empty;

    DestDto IMapTo<DestDto>.MapTo()
    {
        return new DestDto { Id = Id, Value = Value.ToUpper() };
    }
}

// ─── IMapTo: custom implicit impl (SG must skip) ────────────────

public partial class CustomMappedSource : IMapTo<DestDto>
{
    public int Id { get; set; }
    public string Value { get; set; } = string.Empty;

    public DestDto MapTo()
    {
        return new DestDto { Id = Id, Value = "CUSTOM" };
    }
}

// ─── Tests ──────────────────────────────────────────────────────

public class SourceGeneratorTests
{
    private static readonly ProductEntity Hat = new()
    {
        Id = 42,
        Name = "Fedora",
        Price = 89.99m,
        Sku = "FED-001"
    };

    private static readonly SourceRecord Rec = new(7, "Widget");

    // ============================================================
    // IMapFrom — auto-generated (class)
    // ============================================================

    [Fact]
    public void AutoGenerated_SimpleMap_AllPropertiesCopied()
    {
        var dest = new AutoMappedProduct();
        ((IMapFrom<ProductEntity>)dest).MapFrom(Hat);

        Assert.Equal(42, dest.Id);
        Assert.Equal("Fedora", dest.Name);
        Assert.Equal(89.99m, dest.Price);
        Assert.Equal("FED-001", dest.Sku);
    }

    [Fact]
    public void AutoGenerated_MapperMethod_Works()
    {
        var dest = Mapper.Map<ProductEntity, AutoMappedProduct>(Hat);

        Assert.Equal(42, dest.Id);
        Assert.Equal("Fedora", dest.Name);
        Assert.Equal(89.99m, dest.Price);
        Assert.Equal("FED-001", dest.Sku);
    }

    [Fact]
    public void AutoGenerated_MapToExtension_Works()
    {
        var dest = Hat.MapTo<ProductEntity, AutoMappedProduct>();

        Assert.Equal(42, dest.Id);
        Assert.Equal("Fedora", dest.Name);
        Assert.Equal(89.99m, dest.Price);
        Assert.Equal("FED-001", dest.Sku);
    }

    // ============================================================
    // IMapFrom — custom (SG must NOT overwrite)
    // ============================================================

    [Fact]
    public void CustomMap_SkipsAutoGeneration_UsesManualImplementation()
    {
        var dest = Mapper.Map<ProductEntity, CustomMappedProduct>(Hat);

        Assert.Equal(42, dest.Id);
        Assert.Equal("FEDORA", dest.FullName); // manual does ToUpper
        Assert.Equal(89.99m, dest.Price);
        Assert.Equal("FED-001", dest.Sku);
    }

    // ============================================================
    // IMapFrom — record
    // ============================================================

    [Fact]
    public void Record_AutoGeneratedMapFrom_Works()
    {
        var dest = Mapper.Map<SourceRecord, AutoMappedRecord>(Rec);

        Assert.Equal(7, dest.Id);
        Assert.Equal("Widget", dest.Name);
    }

    // ============================================================
    // IMapFrom — struct
    // ============================================================

    [Fact]
    public void Struct_AutoGeneratedMapFrom_Works()
    {
        var dest = Mapper.Map<ProductEntity, AutoMappedStruct>(Hat);

        Assert.Equal(42, dest.Id);
        Assert.Equal("Fedora", dest.Name);
        Assert.Equal(89.99m, dest.Price);
    }

    // ============================================================
    // IMapFrom — explicit interface implementation
    // ============================================================

    [Fact]
    public void ExplicitImplementation_SkipsAutoGeneration()
    {
        var dest = Mapper.Map<ProductEntity, ExplicitMappedDto>(Hat);

        Assert.Equal(42, dest.Id);
        Assert.Equal("FEDORA", dest.Name); // manual impl does ToUpper
    }

    // ============================================================
    // IMapTo — auto-generated
    // ============================================================

    [Fact]
    public void IMapTo_AutoGenerated_Works()
    {
        var source = new AutoMappedSource { Id = 10, Value = "Hello", Extra = "Ingnored" };
        var dest = ((IMapTo<DestDto>)source).MapTo();

        Assert.Equal(10, dest.Id);
        Assert.Equal("Hello", dest.Value);
    }

    // ============================================================
    // IMapTo — explicit impl (SG must skip)
    // ============================================================

    [Fact]
    public void IMapTo_ExplicitImpl_SkipsAutoGeneration()
    {
        var source = new ExplicitMappedSource { Id = 20, Value = "test" };
        var dest = ((IMapTo<DestDto>)source).MapTo();

        Assert.Equal(20, dest.Id);
        Assert.Equal("TEST", dest.Value); // manual does ToUpper
    }

    // ============================================================
    // IMapTo — custom implicit impl (SG must skip)
    // ============================================================

    [Fact]
    public void IMapTo_CustomImpl_SkipsAutoGeneration()
    {
        var source = new CustomMappedSource { Id = 30, Value = "data" };
        var dest = ((IMapTo<DestDto>)source).MapTo();

        Assert.Equal("CUSTOM", dest.Value);
    }

    // ============================================================
    // Non-matching properties
    // ============================================================

    [Fact]
    public void AutoGenerated_PartialProperties_OnlyMatchesAssigned()
    {
        var dest = Mapper.Map<ProductEntity, AutoMappedProduct>(Hat);

        Assert.Equal("Fedora", dest.Name);
        Assert.Equal(89.99m, dest.Price);
    }
}
