<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MapFlow</RootNamespace>
    <Description>Zero-reflection, zero-dependency mapper for .NET. Maps objects via interfaces, selectors, or in-place mutation. Supports PagedResult.</Description>
    <PackageTags>mapper;mapping;dto;pagedresult;automapper</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>MapFlow.png</PackageIcon>
    <PackageReadmeFile>readme.nuget.md</PackageReadmeFile>
    <Authors>MapFlow</Authors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Version>1.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="MapFlow.png" Pack="true" PackagePath="" />
    <None Include="readme.nuget.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MapFlow.SourceGenerator\MapFlow.SourceGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
